- name: Docker create
  hosts: target
  tasks:
    - name: git clone
      ansible.builtin.git:
        repo: http://10.226.47.83:8080/jikuya/jikuya_docker_setup_20.04
        dest: jikuya_docker_setup_20.04
    - name: docker compose
      become: true
      command:
        cmd: 'sudo docker compose up -d'
        chdir: jikuya_docker_setup_20.04